version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: 'circleci/node:10.16.3'
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@6'
      - restore_cache:
          key: 'dependency-cache-{{ checksum "package-lock.json" }}'
      - run:
          name: install-npm
          command: 'npm install'
      - save_cache:
          key: 'dependency-cache-{{ checksum "package-lock.json" }}'
          paths:
            - ./node_modules
      - run:
          name: test
          command: 'npm test'
          environment:
            JEST_JUNIT_OUTPUT_DIR: reports/junit/js-test-results.xml
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
      - store_artifacts:
          path: coverage
      - codecov/upload:
          file: coverage/*.json

